Numpy : Practice Problem

1. Extract all odd numbers from arr


In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==0]

array([0, 2, 4, 6, 8])

2. Replace all odd numbers in arr with -1

In [69]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [5]:
arr=np.arange(10)
np.reshape(arr,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [7]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

Desired Output:
(array([6, 9, 10]),)

In [70]:
a = np.array([2, 6, 1, 9, 10, 3, 27])


6. Create a null vector of size 10 but the fifth value which is 1.

In [24]:
a=np.zeros((10))
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49.

In [17]:
vec=np.arange(10,49)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [72]:
a=np.random.rand(10,10)

print('maximum values is ',np.max(a))
print('minimum value is ',np.min(a))

maximum values is  0.9932831754064643
minimum value is  0.0213463370361493


9. Create a 3*3 matrix and print it's transpose matrix

In [37]:
np.random.seed(10)
arra=np.random.randint(1,30,(3,3))
trans=arra.T
print('before tanspose \n',arra)
print('after transpose \n',trans)

before tanspose 
 [[10  5 16]
 [ 1 18 28]
 [29 26 17]]
after transpose 
 [[10  1 29]
 [ 5 18 26]
 [16 28 17]]


10. Create two arrays of 2-D and find dot product of it.

In [46]:
np.random.seed(100)
a1=np.random.randint(1,35,(3,3))
b1=np.random.randint(1,35,(3,3))
print('a1 is \n',a1,'\nb1 is \n',b1)
print('dot product is \n',np.dot(a1,b1))

a1 is 
 [[ 9 25  4]
 [24 16 11]
 [31  3 15]] 
b1 is 
 [[25 16 17]
 [10 30 23]
 [ 3 28  5]]
dot product is 
 [[ 487 1006  748]
 [ 793 1172  831]
 [ 850 1006  671]]


11. Compute the maximum for each row in the given array.

In [48]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print('marks of students\n',a)
print('maximum marks of each student \n',a.max(axis=1))

marks of students
 [[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
maximum marks of each student 
 [9 8 6 3 9]


12. Select 3rd & 5th row and 3rd & 4th columns

In [53]:
data = np.random.randint(10,100,(5,4))
print(data)
print('answer \n',data[[2,4],2:4])

[[13 94 89 20]
 [97 70 13 58]
 [62 53 46 15]
 [81 48 96 52]
 [94 86 43 68]]
answer 
 [[46 15]
 [43 68]]


13. Convert below matrix into vector

In [55]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print('vector is \n',matrix.flatten())

vector is 
 [1 2 3 4 5 6 7 8 9]


14. The product of two inverse matrix is identical matrix,prove

In [63]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])


inv_m=np.linalg.inv(m)

productof=np.dot(m,inv_m)
print(productof)


[[1. 0.]
 [0. 1.]]


15. Create a matrix from a uniform distribution over [0, 1)

In [65]:
a=np.random.rand(3,3)
print(a)

[[0.56039187 0.2540144  0.9349621 ]
 [0.03424494 0.68654496 0.43893494]
 [0.97772095 0.47738415 0.23895263]]
